name: DevSecOps Pipeline

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Secret scan with Truffle
        uses: trufflesecurity/trufflehog@main
        with: 
            path: ./
            base: ${{ github.event.before }}
            head: ${{ github.sha }}
            extra_args: --only-verified            