name: DevSecOps Pipeline

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
            fetch-depth: 0
        
      - name: Secret scan with Truffle
        uses: trufflesecurity/trufflehog@main
        with: 
            path: ./
            base: ${{ github.event.before }}
            head: ${{ github.sha }}
            extra_args: --only-verified            
    
  sast:
    name:    SAST Analysis
    runs-on: ubuntu-latest
    needs:   build
    permissions:
        actions:         read
        contents:        read
        security-events: write
    
    strategy:
      fail-fast: false
      matrix:
        language: [ 'javascript' ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
            languages: ${{ matrix.language }}
    
      - name: Autobuild
        uses: github/codeql-action/autobuild@v3

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
            category: "/language:${{ matrix.language }}"
     
  sca:
    name:       SCA Analysis
    runs-on:    ubuntu-latest
    needs:      build
    steps:
        - name: Checkout repository
          uses: actions/checkout@v4
        
        - name: OWASP Dependency-Check
          uses: dependency-check/Dependency-Check_Action@main
          with:
            project: 'juice-shop'
            scanPath: '.'
            format: 'HTML'

        - name: Upload Dependency-Check report
          uses: actions/upload-artifact@v4
          with:
            name: dependency-check-report
            path: ${{ runner.workspace }}/dependency-check-report.html